extends: default

ignore: |
  .venv/

rules:
  comments:
    min-spaces-from-content: 1
  document-start: disable
  indentation:
    indent-sequences: whatever
  line-length:
    max: 200
    allow-non-breakable-inline-mappings: true
    allow-non-breakable-words: true
  truthy:
    allowed-values: ["true", "false", "on", "off"]
    check-keys: false
