[settings]
# gix = true
experimental = true
color = true
yes = true
auto_install = true
lockfile = true
# env_shell_expand = true

[settings.python]
uv_venv_auto = true
uv_venv_create_args = "--system-site-packages --seed"

[settings.cargo]
binstall = true

[settings.pipx]
uvx = true

[settings.npm]
bun = true

[tools]
python = "3.13"
uv = "latest"
java = "temurin-21"
"actionlint" = "latest"
action-validator = "latest"
prek = "latest"

[env]
_.file = { path = ".env", tools = true }
_.path = ["{{config_root}}/node_modules/.bin"]
_.python.venv = ".venv"
NODE_ENV = "{{ env.NODE_ENV | default(value='production') }}"
MISE_NPM_PACKAGE_MANAGER = "bun"
PYTHONOPTIMIZE = "1"
