name: Setup Build Environment
description: Sets up Java, Android SDK and Python (via uv) for ReVanced builds
inputs:
  python-version:
    description: Python version to use
    required: false
    default: '3.13'
  java-version:
    description: Java version to use
    required: false
    default: '25'
runs:
  using: composite
  steps:
  - name: Setup Java
    uses: actions/setup-java@v5
    with:
      distribution: temurin
      java-version: ${{ inputs.java-version }}
  - name: Setup Android SDK
    uses: android-actions/setup-android@v3
  - name: Cache Android SDK Build Tools
    uses: actions/cache@v5
    with:
      path: ${{ env.ANDROID_HOME }}/build-tools
      key: ${{ runner.os }}-android-build-tools-34.0.0
      restore-keys: |
        ${{ runner.os }}-android-build-tools-
  - name: Install Android SDK Build Tools
    shell: bash
    run: |
      sdkmanager "build-tools;34.0.0"
      echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH
  - name: Install uv
    uses: astral-sh/setup-uv@v7
    with:
      enable-cache: true
      cache-dependency-glob: "uv.lock"
  - name: Set up Python
    shell: bash
    run: uv python install ${{ inputs.python-version }}
  - name: Install Python dependencies
    shell: bash
    run: uv sync --locked
