name: test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1 # v7.0.1
      - uses: jdx/mise-action@v4.3.0
        with:
          install: true # [default: true] run `mise install`
          experimental: true
          cache: true
          version: "2026.9.0"
      - run: shellcheck scripts/*.sh scripts/lib/*.sh
